// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangTiVi.DATA;

#nullable disable

namespace QuanLyCuaHangTiVi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260125055219_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.QuanLyTiVi", b =>
                {
                    b.Property<string>("MaTiVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("KhuyenMai")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("NgayThangNam")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTiVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTiVi");

                    b.ToTable("QuanLyTiVi");
                });
#pragma warning restore 612, 618
        }
    }
}
