// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangTiVi.DATA;

#nullable disable

namespace QuanLyCuaHangTiVi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaCTPN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPN"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTiVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaCTPN");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaTiVi");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChuHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.HoaDonChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<decimal?>("KhuyenMai")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("MaTiVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("MaTiVi");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayThangNamSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnhChanDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NhanVienMaNhanVien")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.QuanLyTiVi", b =>
                {
                    b.Property<string>("MaTiVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnhMinhHoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HangSanXuat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("KhuyenMai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenTiVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTiVi");

                    b.ToTable("QuanLyTiVi");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.TraGop", b =>
                {
                    b.Property<string>("MaTraGop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KyHanTra")
                        .HasColumnType("int");

                    b.Property<decimal>("LaiSuat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienConNo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("SoTienTraTruoc")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaTraGop");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("TraGop");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyCuaHangTiVi.DATA.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTiVi.DATA.QuanLyTiVi", "QuanLyTiVi")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaTiVi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("QuanLyTiVi");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.HoaDon", b =>
                {
                    b.HasOne("QuanLyCuaHangTiVi.DATA.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTiVi.DATA.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.HoaDonChiTiet", b =>
                {
                    b.HasOne("QuanLyCuaHangTiVi.DATA.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTiVi.DATA.QuanLyTiVi", "QuanLyTiVi")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaTiVi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("QuanLyTiVi");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyCuaHangTiVi.DATA.NhanVien", null)
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NhanVienMaNhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.TraGop", b =>
                {
                    b.HasOne("QuanLyCuaHangTiVi.DATA.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyCuaHangTiVi.DATA.QuanLyTiVi", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("HoaDonChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
